-- Add missing columns to PageView table
ALTER TABLE "PageView" ADD COLUMN IF NOT EXISTS "device" TEXT;
ALTER TABLE "PageView" ADD COLUMN IF NOT EXISTS "browser" TEXT;
ALTER TABLE "PageView" ADD COLUMN IF NOT EXISTS "location" TEXT;
ALTER TABLE "PageView" ADD COLUMN IF NOT EXISTS "referrer" TEXT;
ALTER TABLE "PageView" ADD COLUMN IF NOT EXISTS "timeOnPage" INTEGER;
ALTER TABLE "PageView" ADD COLUMN IF NOT EXISTS "ipAddress" TEXT;
ALTER TABLE "PageView" ADD COLUMN IF NOT EXISTS "userAgent" TEXT;
